#! /usr/bin/env node

var coap = require('coap');

var zclip = require(__dirname + '/../')(coap);
var zcl = require(__dirname + '/lib/zcl')(zclip);
var zclCommand = require(__dirname + '/lib/zclCommand')(process.argv);

zcl(zclCommand, function(error, message, exitCode) {
  if (error)
    console.error(error)

  if (message)
    console.log(message);

  if (exitCode)
    process.exit(exitCode);
});

