#! /usr/bin/env node

var coap = require('coap');

configureCoap(coap);

var zclip = require(__dirname + '/../')(coap);
var zclCommand = require(__dirname + '/lib/zclCommand')(process.argv);
var zcl = require(__dirname + '/lib/zcl')({
  cmd: require(__dirname + '/lib/cmdHandler')(zclip),
  discover: require(__dirname + '/lib/discoverHandler')(zclip),
  read: require(__dirname + '/lib/readHandler')(zclip)
});

var cli = {
  print: console.log,
  printError: console.error,
  exit: process.exit,
  TAB: '  '
}

zcl(zclCommand, cli);

function configureCoap(coap) {
  var coapTiming = {
    ackTimeout: .5,
    ackRandomFactor: 1.0,
    maxRetransmit: 2,
    maxLatency: .5,
    piggybackReplyMs: 10
  };
  coap.updateTiming(coapTiming);
}

