#! /usr/bin/env node

var path = require('path');

global.__appRoot = path.resolve(__dirname) + '/../';

var fs = require('fs');
var async = require('async');
var jsonfile = require('jsonfile');
var importSilabsMetaData = require('./lib/importSilabsMetaData');
var CLUSTER_META_DATA_FILE = './clusterMetaData.json';

var importFiles = process.argv.slice(2);

if (!importFiles.length) {
  console.error('Usage: ./util/importSilabsClusterData ~/clusterMetaData1.xml ~/clusterMetaData2.xml');
  process.exit(1);
}

var clusterMetaData = {};

async.eachSeries(importFiles, importFile, function(err) {
  if (err) {
    console.error('ERR:', err.message || err);
    process.exit(1);
  }

  jsonfile.writeFileSync(CLUSTER_META_DATA_FILE, clusterMetaData, {spaces: 2})
  console.log('Imported successfully to', CLUSTER_META_DATA_FILE);
});

function importFile(file, done) {
  if (!fs.existsSync(file)) {
    done('Cannot find file:', file);
    return;
  }

  console.log('Importing', file);

  var xmlData = fs.readFileSync(file);

  importSilabsMetaData(xmlData, clusterMetaData, function(err) {
    if (err) {
      done(err);
      return;
    }

    done();
  });
}
